# Generated by Django 5.0.6 on 2024-07-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='chai_carieties',
        ),
        migrations.AddField(
            model_name='store',
            name='chai_varities',
            field=models.ManyToManyField(related_name='stores', to='chai.chaivarity'),
        ),
    ]
